# Generated by Django 5.2 on 2025-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="location",
        ),
        migrations.AddField(
            model_name="package",
            name="destination",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="package",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
