# Generated by Django 5.2 on 2025-06-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="tour_count",
        ),
    ]
