# Generated by Django 5.2 on 2025-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_destination_tour_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
