# Generated by Django 5.2.3 on 2025-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_destination_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Use this if you want to embed from Vimeo/YouTube.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
