# Generated by Django 5.2.3 on 2025-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("days", models.IntegerField()),
                ("image", models.ImageField(upload_to="hotels/")),
                ("bathrooms", models.IntegerField(default=1)),
                ("beds", models.IntegerField(default=1)),
                ("rating", models.IntegerField(default=5)),
                (
                    "nearby_attraction",
                    models.CharField(
                        choices=[
                            ("beach", "Near Beach"),
                            ("mountain", "Near Mountain"),
                            ("city", "City Center"),
                            ("desert", "Near Desert"),
                            ("forest", "Near Forest"),
                            ("lake", "Near Lake"),
                            ("none", "No Specific Attraction"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
