# Generated by Django 5.2 on 2025-07-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
