# Generated by Django 5.2 on 2025-07-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_userprofile_aadhar_number_userprofile_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="passport_expiry",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="passport_issue",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="passport_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("nationality", models.CharField(max_length=100)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("passport_issue", models.DateField(blank=True, null=True)),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
