# Generated by Django 5.2 on 2025-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
