# Generated by Django 5.2 on 2025-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_userprofile_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("rating", models.IntegerField(default=5)),
            ],
        ),
    ]
