# Generated by Django 5.2 on 2025-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="package",
            name="beds",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="package",
            name="is_near_beach",
            field=models.BooleanField(default=False),
        ),
    ]
