# Generated by Django 5.2 on 2025-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_package_bathrooms_package_beds_package_is_near_beach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="is_near_beach",
        ),
        migrations.AddField(
            model_name="package",
            name="location_tag",
            field=models.CharField(
                blank=True,
                help_text="Custom location label like 'Near Beach', 'Mountain View', etc.",
                max_length=100,
                null=True,
            ),
        ),
    ]
